namespace Titan.AniTec.Platform.Profile.Interfaces.Resources;

public record UpdateProfileResource(string FirstName, string LastName, string? Phone, string? Bio);
public record ProfileResource(int Id, int UserId, string FirstName, string LastName, string? Phone, string? AvatarUrl, string? Bio);
public record UpdatePreferencesResource(string? Language, string? Theme);
public record PreferencesResource(string Language, string Theme, bool NotificationsEnabled, bool EmailNotifications, bool PushNotifications, bool SmsNotifications);
public record UpdateNotificationSettingsResource(bool? NotificationsEnabled, bool? EmailNotifications, bool? PushNotifications, bool? SmsNotifications);
public record NotificationResource(int Id, string Type, string Title, string Message, bool IsRead, DateTimeOffset? ReadAt, DateTimeOffset CreatedAt);
public record UpdateFarmResource(string FarmName, double? FarmSize, string? Address, string? City, string? State, string? Country, string? PostalCode, double? Latitude, double? Longitude, string? Description);
public record FarmResource(int Id, string FarmName, double? FarmSize, string? Address, string? City, string? State, string? Country, string? PostalCode, double? Latitude, double? Longitude, string? Description);
public record FarmLocationResource(int Id, string Name, string? Description, double? Area);
public record CreateFarmLocationResource(string Name, string? Description, double? Area);
public record UpdateFarmLocationResource(string Name, string? Description, double? Area);
public record FarmStaffResource(int Id, string FullName, string Role, string? Phone, string? Email);
public record CreateFarmStaffResource(string FullName, string Role, string? Phone, string? Email);
public record UpdateFarmStaffResource(string FullName, string Role, string? Phone, string? Email);
public record FarmCertificationResource(int Id, string Name, string IssuingAuthority, DateTimeOffset? IssueDate, DateTimeOffset? ExpiryDate, string? CertificationNumber);
public record CreateFarmCertificationResource(string Name, string IssuingAuthority, DateTimeOffset? IssueDate, DateTimeOffset? ExpiryDate, string? CertificationNumber);
public record UpdateFarmCertificationResource(string Name, string IssuingAuthority, DateTimeOffset? IssueDate, DateTimeOffset? ExpiryDate, string? CertificationNumber);
public record UpdateClinicResource(string ClinicName, string? Address, string? City, string? State, string? Country, string? PostalCode, double? Latitude, double? Longitude, string? Phone, string? Email, string? Description);
public record ClinicResource(int Id, string ClinicName, string? Address, string? City, string? State, string? Country, string? PostalCode, double? Latitude, double? Longitude, string? Phone, string? Email, string? Description);
public record ClinicScheduleResource(DayOfWeek DayOfWeek, TimeSpan OpenTime, TimeSpan CloseTime, bool IsAvailable);
public record UpdateClinicScheduleResource(IReadOnlyCollection<ClinicScheduleItemResource> Schedules);
public record ClinicScheduleItemResource(DayOfWeek DayOfWeek, TimeSpan OpenTime, TimeSpan CloseTime, bool IsAvailable);
public record SpecialtyResource(int Id, string Name, string? Description);
public record CreateSpecialtyResource(string Name, string? Description);
public record ProfessionalLicenseResource(int Id, string LicenseNumber, string IssuingAuthority, DateTimeOffset? IssueDate, DateTimeOffset? ExpiryDate, bool IsVerified);
public record UpdateProfessionalLicenseResource(string LicenseNumber, string IssuingAuthority, DateTimeOffset? IssueDate, DateTimeOffset? ExpiryDate, bool IsVerified);
public record ServiceAreaLocationResource(int Id, string Name, string? Address, double? Latitude, double? Longitude);
public record CreateServiceAreaLocationResource(string Name, string? Address, double? Latitude, double? Longitude);
public record AvailabilityItemResource(DayOfWeek DayOfWeek, TimeSpan StartTime, TimeSpan EndTime, bool IsAvailable);
public record UpdateAvailabilityResource(IReadOnlyCollection<AvailabilityItemResource> Availabilities);
public record AvatarUploadResource(string AvatarUrl);
public record UpdateServiceAreaResource(IReadOnlyCollection<ServiceAreaLocationItemResource> Locations);
public record ServiceAreaLocationItemResource(string Name, string? Address, double? Latitude, double? Longitude);
